name: Node.js CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    - run: |
        # mkdir -p $HOME/.local/bin && \
        # cp -nv ttfautohint.bin $HOME/.local/bin/ttfautohint && \
        # chmod -v 755 $HOME/.local/bin/ttfautohint
        # PATH="$GITHUB_WORKSPACE"/bin:"$PATH"
        chmod -v 755 "$GITHUB_WORKSPACE"/bin/ttfautohint
    - run: npm install
    - run: |
        PATH="$GITHUB_WORKSPACE"/bin:"$PATH"
        # npm run build -- ttf::Iosevka
        # npm run build -- ttf::IosevkaSlab
        # npm run build -- ttf-unhinted::IosevkaN
        npm run build -- ttf-unhinted::IosevkaNStatic
        # npm run build -- ttf-unhinted::IosevkaNTerm
        # npm run build -- ttf-unhinted::IosevkaNFixed
        # npm run build -- ttf-unhinted::IosevkaNSlab
        npm run build -- ttf-unhinted::IosevkaNStaticSlab
        # npm run build -- ttf-unhinted::IosevkaNTermSlab
        # npm run build -- ttf-unhinted::IosevkaNFixedSlab
    - run: |
        mkdir -p ./IosevkaNStatic-x.x.x.x.x && \
        cp -nv dist/IosevkaNStatic/TTF-Unhinted/* IosevkaNStatic-x.x.x.x.x
        mkdir -p ./IosevkaNStaticSlab-x.x.x.x.x && \
        cp -nv dist/IosevkaNStaticSlab/TTF-Unhinted/* IosevkaNStaticSlab-x.x.x.x.x
    - uses: actions/upload-artifact@v4
      with:
        name: IosevkaNStatic-x.x.x.x.x
        path: IosevkaNStatic-x.x.x.x.x
        if-no-files-found: warn
    - uses: actions/upload-artifact@v4
      with:
        name: IosevkaNStaticSlab-x.x.x.x.x
        path: IosevkaNStaticSlab-x.x.x.x.x
        if-no-files-found: warn
